// Bannere products - extracted from extraProducts.ts for better organization
// This file contains all banner-related products

export const BANNERE_PRODUCTS = [
    { id: "banner-curatenie-profesionala", slug: "curatenie-profesionala", routeSlug: "curatenie-profesionala", title: "Banner - Curățenie profesională", description: "Banner pentru servicii de curățenie profesională.", images: ["/products/banner/curatenie-profesionala.jpg"], priceBase: 250, currency: "RON", tags: ["curatenie", "curatenie-profesionala"], metadata: { category: "bannere" } },
    { id: "banner-magazin-second-hand", slug: "magazin-second-hand", routeSlug: "magazin-second-hand", title: "Banner - Magazin second hand", description: "Banner pentru magazine second hand.", images: ["/products/banner/magazin-second-hand.jpg"], priceBase: 250, currency: "RON", tags: ["second-hand", "magazin"], metadata: { category: "bannere" } },
    { id: "banner-magazin-electrocasnice", slug: "magazin-electrocasnice", routeSlug: "magazin-electrocasnice", title: "Banner - Magazin electrocasnice", description: "Banner pentru magazine de electrocasnice.", images: ["/products/banner/magazin-electrocasnice.jpg"], priceBase: 250, currency: "RON", tags: ["electrocasnice", "magazin"], metadata: { category: "bannere" } },
    { id: "banner-magazin-gsm", slug: "magazin-gsm", routeSlug: "magazin-gsm", title: "Banner - Magazin GSM", description: "Banner pentru magazine GSM și accesorii.", images: ["/products/banner/reparam-telefoane.jpg"], priceBase: 250, currency: "RON", tags: ["gsm", "telefoane"], metadata: { category: "bannere" } },
    { id: "banner-service-telefoane", slug: "service-telefoane", routeSlug: "service-telefoane", title: "Banner - Service telefoane", description: "Banner pentru service telefoane și reparații.", images: ["/products/banner/reparam-telefoane.jpg"], priceBase: 250, currency: "RON", tags: ["service", "telefoane"], metadata: { category: "bannere" } },
    { id: "banner-magazin-piese-auto", slug: "magazin-piese-auto", routeSlug: "magazin-piese-auto", title: "Banner - Magazin piese auto", description: "Banner pentru magazine de piese auto.", images: ["/products/banner/piese-auto.jpg"], priceBase: 250, currency: "RON", tags: ["piese-auto", "auto"], metadata: { category: "bannere" } },
    { id: "banner-magazin-decoratiuni", slug: "magazin-decoratiuni", routeSlug: "magazin-decoratiuni", title: "Banner - Magazin decorațiuni", description: "Banner pentru magazine de decorațiuni.", images: ["/products/banner/magazin-decoratiuni.jpg"], priceBase: 250, currency: "RON", tags: ["decoratiuni", "magazin"], metadata: { category: "bannere" } },
    { id: "banner-magazin-papetarie", slug: "magazin-papetarie", routeSlug: "magazin-papetarie", title: "Banner - Magazin papetărie", description: "Banner pentru papetării și rechizite.", images: ["/products/banner/magazin-papetarie.jpg"], priceBase: 250, currency: "RON", tags: ["papetarie", "rechizite"], metadata: { category: "bannere" } },
    { id: "banner-magazin-animale-de-companie", slug: "magazin-animale-de-companie", routeSlug: "magazin-animale-de-companie", title: "Banner - Magazin animale de companie", description: "Banner pentru magazine și produse pentru animale de companie.", priceBase: 250, currency: "RON", tags: ["animale", "pet-shop"], metadata: { category: "bannere" } },
    { id: "banner-pet-shop", slug: "pet-shop", routeSlug: "pet-shop", title: "Banner - Pet Shop", description: "Banner pentru pet shop și produse animale.", images: ["/products/banner/pet-shop.jpg"], priceBase: 250, currency: "RON", tags: ["pet-shop", "animale"], metadata: { category: "bannere" } },
    // ... Add more banner products here as needed
    // Note: For brevity, only showing first 10. The full list from extraProducts.ts should be moved here.
];
