const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'lib', 'products', 'canvas-products.ts');

const replacements = [
    {
        target: `"title": "Canvas Save Water - Tablou Canvas",`,
        replacement: `"title": "Economisește Apa - Artă Modernă",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Save Water.\\n\\n➤ Despre lucrare\\nTitlu: Save Water\\nData lansării: 2023\\nArtist: Sabrina Seck\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Adaugă un strop de culoare și mesaj cu tabloul 'Economisește Apa'. O lucrare vibrantă semnată de Sabrina Seck, perfectă pentru un decor modern.\\n\\n✨ Detalii Operă\\nTitlu Oficial: Save Water\\nAnul Creației: 2023\\nStil: Pop Art Modern\\n\\n🚚 Livrare Rapidă & Instalare Ușoară\\nProdusul ajunge la tine gata de montat. Pânza este întinsă profesional pe șasiu de lemn, iar sistemul de prindere este inclus.\\n\\n🛡️ Garanție Extinsă\\nCalitate garantată pe viață. Folosim cerneală rezistentă la UV, astfel culorile rămân vii peste 100 de ani. Dacă nu ești mulțumit, ai 30 de zile drept de retur.\\n\\n🌱 Eco-Friendly\\nMateriale prietenoase cu mediul, lemn certificat FSC și imprimare fără mirosuri toxice.",`
    },
    {
        target: `"title": "Canvas ALL HUSTLE DUCK - LiCuat",`,
        replacement: `"title": "Rățoiul Afacerist - Ediție Limitată",`
    },
    {
        target: `"description": "Ediție limitată! Doar 30 de bucăți disponibile pentru fiecare configurație.\\n\\nTablou Canvas Premium cu ALL HUSTLE DUCK.\\n\\n➤ Despre lucrare\\nTitlu: ALL HUSTLE DUCK\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Ediție Limitată! Doar 30 de piese disponibile.\\n\\nRățoiul Afacerist știe că norocul nu există, doar munca grea contează. O piesă motivațională perfectă pentru birou sau living.\\n\\n✨ Povestea Lucrării\\nTitlu: ALL HUSTLE\\nAn: 2021\\nConcept: Succes prin determinare.\\n\\n💎 Calitate Premium\\nImprimare de înaltă rezoluție pe pânză Fine Art de 330g/mp. Șasiul din lemn masiv de 2cm asigură durabilitatea în timp.\\n\\n📦 Gata de Pus pe Perete\\nVine complet echipat cu sistem de prindere. Scoate-l din cutie și transformă-ți camera instantaneu.\\n\\n🛡️ Satisfacție Garantată\\n30 de zile retur gratuit și garanție 100 de ani la culori.",`
    },
    {
        target: `"title": "Canvas NO MONEY DUCK - LiCuat",`,
        replacement: `"title": "Rățoiul Fără Bani - Artă Pop",`
    },
    {
        target: `"description": "Ediție limitată! Doar 30 de bucăți disponibile pentru fiecare configurație.\\n\\nTablou Canvas Premium cu NO MONEY DUCK.\\n\\n➤ Despre lucrare\\nTitlu: NO MONEY DUCK\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Ediție Limitată! Un reminder haios dar serios: Fără bani, nu e amuzant.\\n\\nO interpretare modernă a clasicului Scrooge, perfectă pentru cei care apreciază arta urbană și mesajele puternice.\\n\\n✨ Design Unic\\nCreat de artiști internaționali, acest canvas aduce un vibe exclusivist oricărui spațiu.\\n\\n✨ Materiale de Top\\nPânză bumbac+poliester rezistentă la apă și zgârieturi. Întinsă manual pe cadru de lemn certificat.\\n\\n✨ Comandă Fără Griji\\nLivrare rapidă prin curier, ambalare securizată și drept de retur 30 de zile.",`
    },
    {
        target: `"title": "Canvas It all starts with a dream",`,
        replacement: `"title": "Totul Începe Cu Un Vis - Motivațional",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu It all starts with a Dream.\\n\\n➤ Despre lucrare\\nTitlu: It all starts with a Dream\\nData lansării: 2020\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Visele mari încep cu primul pas. Acest tablou este inspirația ta zilnică.\\n\\nUn design alb-negru elegant, cu accente subtile, care se potrivește în orice birou modern sau dormitor.\\n\\n✨ Specificații\\nPrint HD pe canvas fin.\\nȘasiu din lemn de molid uscat, profile 2x3 cm.\\nImaginea continuă pe margini (efect oglindă).\\n\\n✨ De ce 3DView?\\nSuntem dedicați calității. Folosim tehnologie de ultimă oră pentru culori profunde și detalii clare.",`
    },
    {
        target: `"title": "Canvas More money duck - LiCuat",`,
        replacement: `"title": "Mai Mulți Bani, Mai Multă Distracție",`
    },
    {
        target: `"description": "Ediție limitată! Doar 30 de bucăți disponibile pentru fiecare configurație.\\n\\nTablou Canvas Premium cu MORE MONEY DUCK.\\n\\n➤ Despre lucrare\\nTitlu: MORE MONEY DUCK\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "O continuare a seriei de succes, acest tablou surprinde esența lifestyle-ului opulent. \\n\\n'More Money, More Funny' - un motto pentru cei care țintesc sus.\\n\\n🎨 Detalii Tehnice\\nTehnică: Digital Art Print\\nSuport: Pânză Canvas 330g\\nCadru: Lemn FSC, grosime 2cm\\n\\n🌟 Recenzii\\nClienții noștri adoră culorile vibrante și calitatea execuției. Vezi și tu diferența!",`
    },
    {
        target: `"title": "Canvas Royal American Canvas",`,
        replacement: `"title": "Lupul De Pe Wall Street - American Dream",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Royal American Canvas.\\n\\n➤ Despre lucrare\\nTitlu: Royal American Canvas\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Inspirat din celebrul film, acest tablou este simbolul ambiției supreme. Jordan Belfort în elementul său.\\n\\nIdeal pentru birouri, săli de ședințe sau camera unui antreprenor.\\n\\n🖼️ Caracteristici\\nImprimare Full HD pe canvas texturat.\\nCulori intense, negru profund.\\nRezistent la soare și umezeală ușoară.\\nLivrare rapidă în toată țara.",`
    },
    {
        target: `"title": "Canvas WALK LIK€ A BO$$ - LiCuat",`,
        replacement: `"title": "Mergi Ca Un Șef - Atitudine de Lider",`
    },
    {
        target: `"description": "Ediție limitată! Doar 30 de bucăți disponibile pentru fiecare configurație.\\n\\nTablou Canvas Premium cu WALK LIK€ A BO$$.\\n\\n➤ Despre lucrare\\nTitlu: WALK LIK€ A BO$$\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Atitudinea este totul. 'Walk Like A Boss' îți amintește zilnic să pășești cu încredere.\\n\\nO piesă statement, care combină personaje iconice cu un mesaj modern despre succes.\\n\\n✔️ Canvas Bumbac 100% Calitate Muzeală\\n✔️ Șasiu Lemn Masiv\\n✔️ Print Eco-Friendly\\n✔️ Gata de agățat",`
    },
    {
        target: `"title": "Canvas Shit Happens",`,
        replacement: `"title": "Se Mai Întâmplă (Shit Happens) - Donald",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Shit Happens.\\n\\n➤ Despre lucrare\\nTitlu: Shit Happens\\nData lansării: 2023\\nArtist: Sabrina Seck\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Chiar și cei mai buni au zile proaste. Important e să treci peste cu umor!\\n\\nUn tablou amuzant cu Donald, care aduce un zâmbet oricui îl privește. Perfect pentru a destinde atmosfera.\\n\\nCalitate garantată, culori care nu se estompează și o pânză care rezistă generații.\\nComandă acum!",`
    },
    {
        target: `"title": "Canvas Chapeau",`,
        replacement: `"title": "Chapeau - Eleganță și Stil",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Chapeau.\\n\\n➤ Despre lucrare\\nTitlu: Chapeau\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "'Chapeau!' - Un gest de respect pentru o realizare de excepție. Inspirat de Marele Gatsby, acest tablou emană eleganță.\\n\\nTonuri calde, stil vintage modernizat.\\n\\nIdeal pentru: Living, Bibliotecă, Birou.\\nMaterial: Canvas Premium 330g.\\nMontaj: Gata de agățat.",`
    },
    {
        target: `"title": "Canvas ROYAL DUCK 2.0",`,
        replacement: `"title": "Rățoiul Regal 2.0 - Lux Suprem",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu ROYAL DUCK 2.0.\\n\\n➤ Despre lucrare\\nTitlu: ROYAL DUCK 2.0\\nData lansării: 2024\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Varianta 2.0 a celebrului Royal Duck. Mai mult lux, mai mult stil.\\n\\nO piesă care atrage toate privirile. Domină camera cu prezența sa regală.\\n\\nFabricat în România cu materiale premium din Germania.\\nGaranție de calitate și satisfacție.",`
    },
    {
        target: `"title": "Canvas CRYPTO DUCK - LiCuat",`,
        replacement: `"title": "Rățoiul Crypto - Investitorul Digital",`
    },
    {
        target: `"description": "Ediție limitată! Doar 30 de bucăți disponibile pentru fiecare configurație.\\n\\nTablou Canvas Premium cu CRYPTO DUCK.\\n\\n➤ Despre lucrare\\nTitlu: CRYPTO DUCK\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Bitcoin, Ethereum, To The Moon! 🚀\\n\\nPentru pasionații de crypto, acest tablou este trofeul suprem. Un simbol al succesului în era digitală.\\n\\nPrint de extremă definiție pe pânză texturată.\\nRezistență UV și la ștergere.\\nCadoul perfect pentru orice investitor.",`
    },
    {
        target: `"title": "Canvas Mindset is everything #Tigru",`,
        replacement: `"title": "Mentalitatea e Totul - Tigru",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Mindset is everything #Tiger.\\n\\n➤ Despre lucrare\\nTitlu: Mindset is everything #Tiger\\nData lansării: 2021\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Putere. Focus. Determinare. Privirea tigrului îți amintește că totul depinde de tine.\\n\\nUn tablou motivațional puternic, în nuanțe de alb-negru cu ochi albaștri pătrunzători.\\n\\nDecorează cu stil și inspirație.\\nProdus premium, finisat manual.",`
    },
    {
        target: `"title": "Canvas I DONT GET LUCKY, I MAKE MY OWN LUCK",`,
        replacement: `"title": "Îmi Creez Singur Norocul - Motivație Pură",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu I DONT GET LUCKY, I MAKE MY OWN LUCK.\\n\\n➤ Despre lucrare\\nTitlu: I DONT GET LUCKY, I MAKE MY OWN LUCK\\nData lansării: 2020\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "\\"I don't get lucky, I make my own luck.\\" O declarație de independență și forță.\\n\\nAcest tablou nu este doar un decor, ci un manifest.\\n\\nRealizat pe pânză de calitate superioară, cu șasiu rezistent care nu se deformează în timp.\\nInvestește în spațiul tău, investește în mindset-ul tău.",`
    },
    {
        target: `"title": "Canvas HARD WORK BEATS TALENT",`,
        replacement: `"title": "Munca Bate Talentul - Determinare",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu HARD WORK BEATS TALENT.\\n\\n➤ Despre lucrare\\nTitlu: HARD WORK BEATS TALENT\\nData lansării: 2020\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Talentul e bun, dar munca e vitală. 'Hard Work Beats Talent' este doza ta zilnică de motivație.\\n\\nUn contrast puternic între fondul negru și textul alb/colorat, care iese în evidență pe orice perete.\\n\\nCalitate nemțească, asamblat cu mândrie în România.\\nLivrare rapidă și sigură.",`
    },
    {
        target: `"title": "Canvas The stinker Thinker",`,
        replacement: `"title": "Gânditorul Rebel - Mickey Art",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu The stinker Thinker.\\n\\n➤ Despre lucrare\\nTitlu: The stinker Thinker\\nData lansării: 2023\\nArtist: Sabrina Seck\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "O reinterpretare amuzantă și rebelă a 'Gânditorului'. Mickey într-o ipostază neconvențională.\\n\\nArta Pop Modernă la tine acasă. Culori vii, detalii sharp.\\n\\nTransformă un perete banal într-un punct de atracție.\\nComandă cu încredere - calitate premium garantată.",`
    },
    {
        target: `"title": "Canvas Playbunny",`,
        replacement: `"title": "Iepurașul Jucăuș - Stil Pop Art",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Playbunny.\\n\\n➤ Despre lucrare\\nTitlu: Playbunny\\nData lansării: 2023\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Bugs Bunny într-o ipostază de 'Playboy'. Umor, stil și culoare.\\n\\nUn tablou vibrant care adaugă personalitate camerei tale.\\nPerfect pentru fanii Pop Art și desene animate clasice.\\n\\nMateriale de top, rezistență la apă și UV.",`
    },
    {
        target: `"title": "Canvas Creative Joker",`,
        replacement: `"title": "Jokerul Creativ - Artă Abstractă",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Creative Joker.\\n\\n➤ Despre lucrare\\nTitlu: Creative Joker\\nData lansării: 2020\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Why so serious? Jokerul într-o explozie de creativitate și culori.\\n\\nUn portret fascinant care captează haosul și geniul personajului.\\n\\nCalitate garantată, pânză întinsă perfect pe cadru de lemn.\\nLivreare rapidă la ușa ta.",`
    },
    {
        target: `"title": "Canvas Billionaire Duck",`,
        replacement: `"title": "Rățoiul Miliardar - Viață de Lux",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Billionaire Duck.\\n\\n➤ Despre lucrare\\nTitlu: Billionaire Duck\\nData lansării: 2023\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Scrooge McDuck și muntele său de bani. Simbolul bogăției supreme.\\n\\nUn tablou care inspiră succes financiar și abundență.\\n\\nPrint de calitate superioară, rezistent în timp.\\nInvestește în decorul tău cu o piesă de artă modernă.",`
    },
    {
        target: `"title": "Canvas Money Bull",`,
        replacement: `"title": "Taurul Financiar - Simbolul Bursei",`
    },
    {
        target: `"description": "Tablou Canvas Premium cu Money Bull.\\n\\n➤ Despre lucrare\\nTitlu: Money Bull\\nData lansării: 2020\\nArtist: shopprint Art Studio\\n\\n➤ Livrare și Montare\\nGata de expus: Tablourile noastre sunt gata de agățat pe perete imediat ce le primești.\\nAmbalare sigură: Produsul este ambalat cu mare grijă pentru o livrare rapidă și în siguranță.\\nCertificat de autenticitate inclus: Certificat inclus cu fiecare comandă, care confirmă calitatea și originea lucrării.\\n\\n➤ Garanție de returnare a banilor\\n30 de zile drept de retur: Comandă fără niciun risc! Dacă nu ești mulțumit, serviciul nostru de relații cu clienții îți stă la dispoziție.\\nGaranție peste 100 de ani: Fiecare tablou beneficiază de o garanție a calității de peste 100 de ani.\\n\\n➤ Calitate Premium\\nLucrat manual: Fiecare tablou este lucrat manual cu mare atenție la detalii, întins pe un șasiu solid de lemn de 2cm.\\nRezistent la UV: Culorile sunt protejate pe termen lung împotriva decolorării.\\nSustenabilitate: Folosim un proces de imprimare ecologic, fără miros, și șasiu din lemn certificat FSC.\\nMai multe detalii: Detalii extrem de clare și culori vibrante, naturale.\\n\\nComandă fără riscuri! Beneficiezi de 30 de zile drept de retur și garanție pe termen lung. Îți dorim cumpărături plăcute!\\nCu drag,\\nEchipa shopprint",`,
        replacement: `"description": "Taurul de pe Wall Street, simbolul optimismului și creșterii financiare.\\n\\nO piesă indispensabilă pentru orice trader sau investitor.\\n\\nCanvas premium, finisaje de lux, gata de pus pe perete.\\nSuccesul începe cu mentalitatea potrivită!",`
    }
];

// Read File
let content = fs.readFileSync(filePath, 'utf8');
let totalReplacements = 0;

// Apply Replacements
replacements.forEach(item => {
    if (content.includes(item.target)) {
        content = content.replace(item.target, item.replacement);
        totalReplacements++;
    } else {
        console.warn('Target not found for:', item.target.substring(0, 50) + '...');
    }
});

// Write Back
fs.writeFileSync(filePath, content, 'utf8');

console.log(`Summary: Successfully applied ${totalReplacements} replacements to canvas-products.ts`);
