export const PRODUCT_INTENTS: Record<string, string[]> = {
    'banner': ['de-vanzare', 'de-inchiriat', 'deschidere-magazin', 'electoral', 'promotie', 'reducere', 'santier', 'publicitar', 'buzunare', 'capse-dese'],
    'afise': ['concert', 'eveniment', 'electoral', 'promotie', 'film', 'conferinta', 'oferta', 'happy-hour', 'horeca'],
    'canvas': ['nunta', 'botez', 'familie', 'peisaj', 'cadou-aniversare', 'colaj-foto', 'abstract', 'modern', 'rama-neagra', 'rama-alba'],
    'autocolante': ['program-functionare', 'logo-firma', 'geamuri', 'decorativ', 'perete', 'vinyl', 'promotie', 'transparent', 'lucios', 'mat', 'window-graphics', 'imobiliare'],
    'rollup': ['expozitie', 'conferinta', 'prezentare', 'eveniment', 'receptie'],
    'pliante': ['meniu', 'servicii', 'prezentare', 'oferta', 'turism', 'horeca'],
    'tricouri': ['personalizat', 'cadou', 'echipa', 'eveniment', 'funny'],
    'carti-vizita': ['standard', 'premium', 'avocat', 'doctor', 'constructii', 'salon', 'imobiliare'],
    'plexiglass': ['avocat', 'doctor', 'placa-sediu', 'transparent', 'alb'],
};

// Global marketing terms for all products
export const MARKETING_INTENTS = [
    'personalizat', 'ieftin', 'pret-mic', 'rapid', 'urgent', 'premium', 'online', 'lux', 'hd', 'profesional', 'calitate'
];

export const INTENT_LABELS: Record<string, string> = {
    'de-vanzare': 'De Vânzare',
    'de-inchiriat': 'De Închiriat',
    'deschidere-magazin': 'Deschidere Magazin',
    'electoral': 'Electoral',
    'promotie': 'Promoție',
    'reducere': 'Reducere',
    'santier': 'Șantier în Lucru',
    'publicitar': 'Publicitar',
    'concert': 'Concert',
    'eveniment': 'Eveniment / Party',
    'film': 'Film',
    'conferinta': 'Conferință',
    'oferta': 'Ofertă Specială',
    'nunta': 'Nuntă',
    'botez': 'Botez',
    'familie': 'Familie',
    'peisaj': 'Peisaj',
    'cadou-aniversare': 'Cadou Aniversare',
    'colaj-foto': 'Colaj Foto',
    'abstract': 'Abstract',
    'modern': 'Modern',
    'program-functionare': 'Program Funcționare',
    'logo-firma': 'Logo Firmă',
    'geamuri': 'Geamuri',
    'decorativ': 'Decorativ',
    'perete': 'Perete',
    'vinyl': 'Vinyl',
    'expozitie': 'Expoziție',
    'prezentare': 'Prezentare',
    'receptie': 'Recepție',
    'meniu': 'Meniu',
    'servicii': 'Servicii',
    'turism': 'Turism',
    'personalizat': 'Personalizat',
    'cadou': 'Cadou',
    'echipa': 'Echipă',
    'funny': 'Funny / Amuzant',
    'standard': 'Standard',
    'premium': 'Premium',
    'avocat': 'Avocat',
    'doctor': 'Doctor / Medic',
    'constructii': 'Construcții',
    'salon': 'Salon / Cosmetică',
    'imobiliare': 'Imobiliare',
    'transparent': 'Transparent',
    'lucios': 'Lucios',
    'mat': 'Mat',
    'buzunare': 'Cu Buzunare',
    'capse-dese': 'Cu Capse Dese',
    'rama-neagra': 'Cu Ramă Neagră',
    'rama-alba': 'Cu Ramă Albă',
    'happy-hour': 'Happy Hour',
    'horeca': 'Horeca / Restaurant',
    'placa-sediu': 'Placă Sediu',
    'window-graphics': 'Window Graphics',
    'alb': 'Alb',
    // Marketing Specific
    'ieftin': 'Ieftin',
    'pret-mic': 'Preț Mic',
    'rapid': 'Rapid',
    'urgent': 'Urgent',
    'online': 'Online',
    'lux': 'Lux',
    'hd': 'High Definition (HD)',
    'profesional': 'Profesional',
    'calitate': 'Calitate',
    'frontlit': 'Frontlit (Standard)',
    'mesh': 'Mesh (Perforat)',
};
